spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}